### ISSUE TITLE
Formats not in json

### ISSUE THREAD

**Issue by moturiphil** [bibleapi/bibleapi-bibles-json#2]
Checkout for pull request

**Comment by rkazakov** [comment]
@Phil-Reck Merged, thanks.

**Comment by moturiphil** [comment]
Hi Bibleapi/Bibleapi-Bibles-Json,

Been trying to push changes on the repo, but don't have permissions...

**Comment by rkazakov** [comment]
@Phil-Reck You need to fork the repo into your account.

**Comment by moturiphil** [comment]
Pls, checkout the pull request, the json done are for asv and kjv
translation only.

Thanks.
